### ISSUE TITLE
onKeyDown中延迟不会被检测到。

### ISSUE THREAD

**Issue by dede1314** [markzhai/AndroidPerformanceMonitor#102]
自己在测试中发现如下问题：
1 onClick 中 有如下代码，能够被检测到，且生成log.
findViewById(R.id.btn).setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    try {
                        Thread.sleep(30000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            });

2 但是在onKeyDown 中有如下测试代码：
  if (keyCode == KeyEvent.KEYCODE_E) {
                Thread.sleep(30000);
}
但这种情况下，并没有检测到，也没有log 生成。sleep 时间改到60s  也没有检测到。

3 请问为什么在onKeyDown 中为什么就检测不到了？

**Comment by markzhai** [comment]
onKeyDown 这里打印一下所在线程，看看是不是主线程

**Comment by dede1314** [comment]
onKeyDown 是在主线程的。

**Comment by dede1314** [comment]
通过adb input keyevent E的方式让主线程sleep 30秒，不会被检测到。
如果是通过物理按键，就可以检测到。

一个奇怪的问题是模拟按键输入让主线程sleep 30秒不会产生anr.  但是通过物理按键的方式让主线程sleep 30秒却会产生anr。难道模拟按键输入和物理按键输入 系统会做不同的处理吗？

**Comment by aesean** [comment]
onKeyDown确实是不会被检测到的。因为onKeyDown传递到Activity并不会经过Handler。
详细的可以参考这里：http://www.jianshu.com/p/9849026e7232

**Comment by dede1314** [comment]
但onClick 中可以检测到，而onkeydown 和onTouchEvent 检测不到。onKeyDown传递到Activity并不会经过Handler。但点击事件经过handle.  可以这样理解吗 ？  同样是触摸事件，怎么差距这么大

**Comment by aesean** [comment]
@dede1314  是否能被检测到主要是看对应代码是否是经过Handler执行的。我那篇文章有写。
你想要查看某个代码是否经过Handler可以采用文章中的方法，在想要查看的地方打一个断点，然后在IDE的debug界面左边从上往下数第7个小图标get thread dump，然后查看当前断电的调用方法堆栈是否是从Handler过来的。
看到类似下面的堆栈就是从Handler过来的。
```
          at android.os.Handler.handleCallback(Handler.java:751)
	  at android.os.Handler.dispatchMessage(Handler.java:95)
	  at android.os.Looper.loop(Looper.java:154)
	  at android.app.ActivityThread.main(ActivityThread.java:6119)
	  at java.lang.reflect.Method.invoke(Method.java:-1)
```
但是这个就显然不是
```
      at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6349)
      at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
      at android.os.MessageQueue.nativePollOnce(MessageQueue.java:-1)
      at android.os.MessageQueue.next(MessageQueue.java:323)
      at android.os.Looper.loop(Looper.java:136)
```

**Comment by aesean** [comment]
另外你说的OnClick能被检测到，如果非要刨根问底的话就是因为OnClick被Handler重新分发了。那具体是在哪里post的呢？是View的onTouchEvent方法里，找到
                                if (!post(mPerformClick)) {
                                    performClick();
                                }
然后跟进if条件里那个post方法，
attachInfo.mHandler.post(action);
实际是这一行代码把Touch操作重新以Handler消息形式分发了。所以在这之前的所有代码都没有经过Handler，就导致了你在Activity的OnTouch里无法检测到ANR的问题了。
