### ISSUE TITLE
关于ANR的问题

### ISSUE THREAD

**Issue by huangqichao** [markzhai/AndroidPerformanceMonitor#104]
当程序ANR的时候，dispatchMessage阻塞，因此无法走到第二个println方法，请问作者觉得有什么好的处理方式吗？我目前的处理方式是每次dump堆栈时候计算一下这条消息已经执行了多久，如果超过5秒就直接收集信息然后结束掉了。有没有什么更好的办法？

**Comment by dede1314** [comment]
现在主线程sleep了很久（原因正在排查中），和上面的类似，也是dispatchMessage阻塞，因此无法走到第二个println方法。
此时就不能正常起作用了

**Comment by markzhai** [comment]
你都 ANR 了，当然是用 ANR 的信息去找哪里出问题了，还用这个干啥？去用还原 ANR 场景的那些方法。这个就是用来找出那些还不至于 ANR 的毒瘤的。
