### ISSUE TITLE
println的问题

### ISSUE THREAD

**Issue by peanhuang** [markzhai/AndroidPerformanceMonitor#111]
println开始和结束时间差，wall time是几十秒，但是thread time 是1毫秒甚至0毫秒，这是什么情况？
这种情况没有stack和cpu采样信息。

eg：

time = 118634
thread-time = 1
time-start = 09-25 11:03:56.624
time-end = 09-25 11:05:55.258

**Comment by markzhai** [comment]
@peanhuang 线程没有获得执行时间

**Comment by peanhuang** [comment]
是的，这种场景主线程没有得到cpu执行时间，抓stack和cpu采样信息的线程也没得到执行。我其实想说的具体是什么场景下会出现这种奇怪的现象？是有某些特殊消息？

**Comment by peanhuang** [comment]
@markzhai
