### ISSUE TITLE
刚安装完APP，点击桌面的Blocks ICON启动，空指针异常

### ISSUE THREAD

**Issue by kesenhoo** [markzhai/AndroidPerformanceMonitor#46]
生成APK，安装到手机，选择点击桌面自动生成的Blocks图标，出现空指针异常
![image](https://cloud.githubusercontent.com/assets/1456490/14736067/4aabca02-08a7-11e6-9c39-a4d905fa3850.png)

**Comment by markzhai** [comment]
应该是没有文件，或者文件没读出来field导致的...

**Comment by markzhai** [comment]
https://github.com/markzhai/AndroidPerformanceMonitor/commit/5859d7fbbada2fccf9cf86c86a4dff840d1098f8
