### ISSUE TITLE
NullPointerException: Attempt to invoke interface method 'java.lang.String com.github.moduth.blockcanary.IBlockCanaryContext.getLogPath()'

### ISSUE THREAD

**Issue by liuxin85611** [markzhai/AndroidPerformanceMonitor#52]
06-02 18:07:50.253 E/AndroidRuntime(27493): FATAL EXCEPTION: pool-7-thread-1

06-02 18:07:50.253 E/AndroidRuntime(27493): Process: com.youku.phone, PID: 27493

06-02 18:07:50.253 E/AndroidRuntime(27493): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.github.moduth.blockcanary.IBlockCanaryContext.getLogPath()' on a null object reference

06-02 18:07:50.253 E/AndroidRuntime(27493): 	at com.github.moduth.blockcanary.log.BlockCanaryInternals.getPath(BlockCanaryInternals.java:30)

06-02 18:07:50.253 E/AndroidRuntime(27493): 	at com.github.moduth.blockcanary.log.BlockCanaryInternals.detectedLeakDirectory(BlockCanaryInternals.java:38)

06-02 18:07:50.253 E/AndroidRuntime(27493): 	at com.github.moduth.blockcanary.log.BlockCanaryInternals.getLogFiles(BlockCanaryInternals.java:46)

06-02 18:07:50.253 E/AndroidRuntime(27493): 	at com.github.moduth.blockcanary.ui.DisplayBlockActivity$LoadBlocks.run(DisplayBlockActivity.java:395)

06-02 18:07:50.253 E/AndroidRuntime(27493): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)

06-02 18:07:50.253 E/AndroidRuntime(27493): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)

06-02 18:07:50.253 E/AndroidRuntime(27493): 	at java.lang.Thread.run(Thread.java:818)

**Comment by markzhai** [comment]
应该是直接打开了Blocks，还没有开启自己的应用吧，这时候 `BlockCanaryContext` 是空，所以当然会crash
