### ISSUE TITLE
can't import in gradle 

### ISSUE THREAD

**Issue by zhuruyi2013** [markzhai/AndroidPerformanceMonitor#65]
detail error :
Error:Could not find AndroidPerformanceMonitor:blockcanary-analyzer:unspecified.
Required by:
    tvbox:box:unspecified > com.github.moduth:blockcanary-android:1.3.1

**Comment by markzhai** [comment]
dependencies {
    // most often used way, enable notification to notify block event
    compile 'com.github.markzhai:blockcanary-android:1.3.1'

    // this way you only enable BlockCanary in debug package
    // debugCompile 'com.github.markzhai:blockcanary-android:1.3.1'
    // releaseCompile 'com.github.markzhai:blockcanary-no-op:1.3.1'
}

Please use this, sorry for mistake in readme
