### ISSUE TITLE
申请一下修改许可

### ISSUE THREAD

**Issue by kiruto** [markzhai/AndroidPerformanceMonitor#66]
hi作者您好，您的项目我非常喜欢，非常实用。拜读过您的作品后我用kotlin将Block Canary复写了一下，用来兼容Kotlin代码检测。同时我还加入了一些其它功能，我把它开源并放在了这里
https://github.com/kiruto/debug-bottle
同时附上了您项目的链接和许可证，请问我可以这样做，并应用于我的项目吗？感谢过目

**Comment by markzhai** [comment]
@kiruto 没有问题哈

**Comment by kiruto** [comment]
@markzhai 非常感谢
