### ISSUE TITLE
支持自定义Block之后的动作吗？

### ISSUE THREAD

**Issue by liuzhao2007** [markzhai/AndroidPerformanceMonitor#68]
例如，自定义Block之后让App崩溃掉或者是弹出对话框之类的？

**Comment by markzhai** [comment]
@liuzhao2007 可以加上，谢谢建议。。不过让App崩溃掉是什么梗

**Comment by markzhai** [comment]
@liuzhao2007 主要应用场景是什么？

**Comment by liuzhao2007** [comment]
让程序崩溃不是必须的，支持自定义操作的话可以自己实现了；我是想做个强制的操作，引起重视。

**Comment by markzhai** [comment]
改好发布了，见 1.4.0
