### ISSUE TITLE
卡顿日志界面没有显示内容

### ISSUE THREAD

**Issue by jerry0864** [markzhai/AndroidPerformanceMonitor#69]
通知栏有显示卡顿通知图标，下拉通知栏点击进入卡顿日志界面，显示空白。SD卡日志也有写成功。
![device-2016-09-21-135157](https://cloud.githubusercontent.com/assets/4986598/18699262/d54374da-8002-11e6-8271-b043f8b0ea1a.png)

**Comment by markzhai** [comment]
sd卡里面确实有文件吗？看一下

**Comment by jerry0864** [comment]
@markzhai 我换了1.2.1版本后，是可以正常显示日志的。最新的1.3.1显示不了，1.3.1确实是有日志保存在SD卡上的，我有用RE管理器打开查看。

**Comment by markzhai** [comment]
@jerry0864 1.3.1有做过滤的，文件在的话，可能是被你的过滤策略过滤了

**Comment by jerry0864** [comment]
@markzhai 嗯，你说的对。我之前没有实现concernPackages方法，直接return null。现在 实现concernPackages后，把包名添加进来，显示正常了。谢谢！
