### ISSUE TITLE
No resource found

### ISSUE THREAD

**Issue by calvinHB** [markzhai/AndroidPerformanceMonitor#7]
/XXXX/build/intermediates/exploded-aar/com.github.moduth/blockcanary/1.0.0/res/values-v21/values-v21.xml
Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:Theme.Material'.

**Comment by markzhai** [comment]
Doesn't happen to me, can you offer your compileSdkVersion and targetSdkVersion, maybe caused by targetSdkVersion

**Comment by calvinHB** [comment]
My Project compileSdkVersion is 14, that compileSdkVersion is 23, so style.xml not have 'android:Theme.Material'

**Comment by markzhai** [comment]
I see, I would try to make compatability for lower sdk version.
