### ISSUE TITLE
分享完毕回到App之后删除按钮失灵

### ISSUE THREAD

**Issue by tanglie1993** [markzhai/AndroidPerformanceMonitor#75]
我认为这个bug的原因是这样的：
DisplayActivity renderBlockDetail(final BlockInfoEx blockInfo)的第三行if (listAdapter instanceof DetailAdapter)在此时为true，故不会执行mActionButton.setOnClickListener方法。
然而，此时的mBlockInfoEntries已经被LoadBlocks刷新过一遍。所以，在mActionButton的点击事件被执行时，其onclick方法中blockInfo变量指向的对象就过时了，它不在刷新后的mBlockInfoEntries中。因此mBlockInfoEntries.remove(blockInfo)也就无效了。
你觉得对不对？

**Comment by markzhai** [comment]
https://github.com/markzhai/AndroidPerformanceMonitor/pull/76
