### ISSUE TITLE
上传日志

### ISSUE THREAD

**Issue by xingzjx** [markzhai/AndroidPerformanceMonitor#83]
你好，怎么把收集到的日志上传到服务端，AppBlockCanaryContext的upload方法在收到log后也无法执行

**Comment by markzhai** [comment]
需要手动调用 `BlockCanary.get().upload`，见 https://github.com/markzhai/AndroidPerformanceMonitor/blob/master/blockcanary-android/src/main/java/com/github/moduth/blockcanary/BlockCanary.java#L106

**Comment by xingzjx** [comment]
BlockCanary blockCanary =  BlockCanary.install(this, new AppBlockCanaryContext());
blockCanary.start();
blockCanary.upload();
在Application调用以上代码，然后AppBlockCanaryContext的zip方法调用了，但是upload还是没法调用？

**Comment by markzhai** [comment]
@xingzjx 

zip 返回的 file.exists() 才会真正 upload

**Comment by markzhai** [comment]
没问题的话我就关了

**Comment by xingzjx** [comment]
private static File zip() {
    String timeString = Long.toString(System.currentTimeMillis());
    try {
        timeString = FORMAT.format(new Date());
    } catch (Throwable e) {
        Log.e(TAG, "zip: ", e);
    }
    File zippedFile = LogWriter.generateTempZip("BlockCanary-" + timeString);
    BlockCanaryInternals.getContext().zip(BlockCanaryInternals.getLogFiles(), zippedFile);
    LogWriter.deleteAll();
    return zippedFile;
}
这个方法返回的是临时文件，被LogWriter.deleteAll()删除了，file.exists()总是false

**Comment by xingzjx** [comment]
所以，upload还是无法执行啊，

**Comment by markzhai** [comment]
@xingzjx deleteAll 为什么会删除？

**Comment by markzhai** [comment]
这个方法返回的文件当然不能放在原来的目录里

**Comment by xingzjx** [comment]
ok

**Comment by xingzjx** [comment]
ok，有没有办法获取日志的类型（如Native Method Blocked），等方便后台过滤的信息

**Comment by markzhai** [comment]
这个应该让后台自己去过滤了

**Comment by xingzjx** [comment]
后台怎么知道这个log是Native Method Blocked

**Comment by xingzjx** [comment]
从日志当中好像无法得知Native Method Blocked这种类型？

**Comment by markzhai** [comment]
当然有办法啊，堆栈里写清楚是 Native Method 的

**Comment by xingzjx** [comment]
明白了，谢谢了
