### ISSUE TITLE
Conflic when use with Webview

### ISSUE THREAD

**Issue by thanhlv93** [markzhai/AndroidPerformanceMonitor#98]
Hi All,
I have issue about use BlockCanary when I have an Activity using Webview . After Webview is inflated , method setMessageLogging called by Android System and LooperMonitor instead null , so method println(String x) in LooperMonitor not called.

Can you tell my how to fix this issue ?

**Comment by huangqichao** [comment]
The webview set the logging null in the native code, and only once! You can add a breakpoint in setMessageLogging and read the trace ,you'll find out where does the webview do this.
new a webview before initlize blockcanary will solve this problem,after that ,the webview will not set mainlooper's logging null any time.

**Comment by suntzu93** [comment]
@huangqichao Thank you for your answer. I resolved my issue by way initlize webview before blockcanary.

**Comment by markzhai** [comment]
Thanks @huangqichao 's help.
